### ISSUE TITLE
flicker? lines across monitor

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#101]
When I have the blue light reduction stepped down, I start to see faint horizontal lines across the monitor. These get more pronounced if I also have the brightness reduced...
I’m lowering the brightness using Iris, not the monitor
not sure how to capture a video of this as anything local on the computer (snipping tool or screen recording) doesn’t pick up the artefacts and recording with my phone shows up lots of unrelated noise and color artefacts just due to the refresh rate etc and it’s impossible to see the horizontal lines I’m referring to…

**High level API doesn't work**
screen overlay also doesn't work

Iris version is 0.9.4. **(newer version also doesn't fix the problem)**
Windows 10 x64 1803

https://iristechnologies-help.zendesk.com/agent/tickets/18020

**Comment by danielng01** [comment]
Set your monitor hardware brightness to the maximum
https://iristech.co/how-to-setup-iris-for-maximum-eye-health/

add this as FAQ

**Comment by valeksa1428** [comment]
https://iristech.co/faq/how-to-reduce-flicker/
