### ISSUE TITLE
timer sounds work even when turned off

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#105]
I am getting audible warnings at each notification of the upcoming rest period. 'Use Sounds' is not on on the Timer screen and is saved as such, yet i continue to receive ping sounds at each warning. I do not want sounds interrupting my thoughts

----------
App model: Iris
App version: 1.1.9

----------
OS: windows
Model: Windows 8
Architecture: x86_64

----------
System info
Build abi: i386-little_endian-ilp32
Build CPU Architecture: i386
Current CPU Architecture: x86_64
Kernel Type: winnt
Kernel Version: 6.2.18362
Pretty Product Name: Windows 8
Product Type: windows
Product Version: 8

----------
CPU info
CPU type: Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz
CPU cores: 4
CPU speed: 1995Mhz

----------
Motherboard info
BIOSReleaseDate: 10/22/2014
BIOSVendor: Hewlett-Packard
BIOSVersion: L04 v02.10
BaseBoardManufacturer: Hewlett-Packard
BaseBoardProduct: 1825
BaseBoardVersion:
BiosMajorRelease: 2
BiosMinorRelease: 10
ECFirmwareMajorRelease: 255
ECFirmwareMinorRelease: 255
SystemFamily: 103C_53307F G=D
SystemManufacturer: Hewlett-Packard
SystemProductName: HP EliteDesk 800 G1 DM
SystemSKU: K5Q70UC#ABA
SystemVersion:

----------
Current settings
ActivationCode: eBPD
AdvancedColorEffect: 1
AdvancedDayBrightness: 61
AdvancedDayDim: 0
AdvancedDayOpacity: 5
AdvancedDayTemperature: 3185
AdvancedLightnessScreenOpacity: 30
AdvancedLightnessScreenRadius: 30
AdvancedLightnessScreenXposition: 50
AdvancedLightnessScreenYPosition: 50
AdvancedNightBrightness: 58
AdvancedNightDim: 10
AdvancedNightOpacity: 40
AdvancedNightTemperature: 3400
AdvancedSleepBrightness: 46
AdvancedSleepLight: 2700
AdvancedUseColorEffects: false
AdvancedUseInvertedColors: false
AdvancedUseLightnessScreen: false
AdvancedUseManualBrightness: false
AdvancedUseManualColorSettings: false
AdvancedUseOverlayScreen: false
AdvancedUseSleepLight: true
AdvancedView: true
AllowMultipleInstances: false
ApplicationsForBlocking:
AutoCloseRest: true
AutosaveSettings: true
BedtimeHours: 0
BedtimeMinutes: 0
CameraActive: false
CheckForUpdates: false
ColorChangesPaused: false
ColorEffect: 1
ColorPausers: Photoshop.exe
3dsmax.exe
blender.exe
maya.exe
ColorPausersPauseOnFullscreenApps: false
ColorScheme: 1
ColorTriggers: vlc.exe = 6500 120
mpc-hc64.exe = 6500 120
DayBrightness: 61
DayBrightness1: 100
DayDim: 0
DayOpacity: 5
DayTemperature: 3185
DayTemperature1: 5000
DayTransitionDuration: 3600
DecreaseBrightnessHotkey: Ctrl+Alt+PgDown
DecreaseBrightnessStep: 10
DecreaseTemperatureHotkey: Ctrl+Alt+Down
DecreaseTemperatureStep: 500
DestroyUiOnClose: false
EnableConflictingApplications: false
EndOverlayScreenHotkey: Ctrl+Alt+End
FontType: 3
FullMoonOffset: 1200
HardwareBrightnessLimit: 100
HideTaskbarIcon: true
IncreaseBrightnessHotkey: Ctrl+Alt+PgUp
IncreaseBrightnessStep: 10
IncreaseTemperatureHotkey: Ctrl+Alt+Up
IncreaseTemperatureStep: 500
IrisMode: 2
IrisPaused: false
IrisType: 0
IrisUpdateInterval: 10000
IsFirstStart: false
IsModelIrisLite: false
IsTrial: false
Language: en
LastCheckedDailyUsageOn:
LeadingColor: 1
LightnessScreenOpacity: 30
LightnessScreenRadius: 30
LightnessScreenXPosition: 50
LightnessScreenYPosition: 50
ManualAutomaticToggleHotkey: Ctrl+Alt+M
MatchBrightnessToLighting: false
MouseClickInterval: 1000
MousePausers: Dota.exe
WOW.exe
hl.exe
OtherGame.exe
MousePausersPauseOnFullscreenApps: true
NewMoonOffset: 300
NightBrightness: 58
NightBrightness1: 80
NightDim: 10
NightEndTimeHours: 6
NightEndTimeMinutes: 0
NightOpacity: 40
NightStartTimeHours: 20
NightStartTimeMinutes: 0
NightTemperature: 3400
NightTemperature1: 3400
NightTransitionDuration: 3600
OptimizeUiCreation: true
OverlayScreenColor: 9
OverlayScreenEndMousePosition:
OverlayScreenStartMousePosition:
PWMFrequency: -1
PWMMaxFrequency: 2000
PageToOpen: Timer
PauseResumeIrisHotkey: Ctrl+Alt+P
PauseResumeTimerHotkey: Ctrl+Alt+T
PauseTransitionDuration: 1000
PostponeTime: 10
PreserveGamma: true
QuitIrisHotkey: Ctrl+Alt+Esc
RestScreenType: 2
RestTime: 40
Saturation: 91
SleepBrightness: 46
SleepBrightness1: 75
SleepLight: 2700
SleepLight1: 2700
SleepTransitionDuration: 3600
SmartBrightness: false
SmartInversion: false
SmoothColorsUpdateInterval: 25
StartOnStartup: true
StartOverlayScreenHotkey: Ctrl+Alt+Home
StartRestHotkey: Ctrl+Alt+Enter
TimeZoneOffset: 0
TimerPaused: false
TimerPausers: KMPlayer.exe
vlc.exe
bsplayer.exe
TimerPausersPauseOnFullscreenApps: true
TimerType: 2
TrialId: eVcfE
TrialRemaining: 0
UiScale: 0
UnusedPages:
UpdateContinuously: true
UpdatesInterval: 1
UseAutomaticBrightness: false
UseBigRestIncomingNotification: true
UseBlinkDetection: false
UseBlinkScreen: false
UseBrightnessExtendedValues: false
UseColorEffects: false
UseColorEffectsHotkey: Ctrl+Alt+R
UseColorPausers: false
UseColorTriggers: false
UseGammaFixer: true
UseGhostIcon: false
UseHardwareBrightness: false
UseHiddenFeaturesNotifications: true
UseInvertedColors: false
UseKeyboardBlocking: false
UseKeyboardHook: true
UseKeyboardInactivity: false
UseKeyboardShortcuts: false
UseLightnessScreen: false
UseLowLevelColorApi: true
UseManualBrightness: false
UseManualColorSettings: false
UseManualLocation: false
UseManualNightDuration: false
UseMouseInactivity: false
UseMousePausers: false
UseOverlayScreen: false
UsePWMControl: false
UsePerMonitorSettings: false
UsePostponeNotification: true
UseSaturation: false
UseSleepLight: true
UseSoftwareCursor: false
UseSounds: false
UseSpinningTrayIcon: true
UseTemperatureExtendedValues: false
UseTimerPausers: false
UseTrialNotification: true
WakeTimeHours: 4
WakeTimeMinutes: 0
WebsitesForBlocking:
WorkTime: 40
ZoomInHotkey: Ctrl+Alt++
ZoomOutHotkey: Ctrl+Alt+-

----------
Saved settings
ApiArguments:   show_ui
CLICK TO COPY THE TEXT TO CLIPBOARD

https://iristechnologies-help.zendesk.com/agent/tickets/18224

**Comment by danielng01** [comment]
You can use this:
https://iristech.co/iris-hidden-features/#big-rest-incoming-notification
:)

**Comment by danielng01** [comment]
Add this as FAQ to the website

**Comment by valeksa1428** [comment]
https://iristech.co/faq/how-to-stop-timer-sounds/
