### ISSUE TITLE
iris flashes on new mac catalina - bonus issue

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#106]
high level api fixes the flashing but iris stops changing screen colors
-----
That removed the flickering but the hue is not changing.
Black and white still works.
the issue is the same regardless of whether i selecte "use advanced settings"

**VIDEO OF ISSUE - IN TICKET**

BONUS - debug menu doesn't show full text

-----------------------------------------------------------------------------------
Iris version: 0.9.2.2
Iris model: Iris Pro

OS: Windows
Model: Windows 7
Architecture: x86
-----------------------------------------------------------------------------------

Saved settings
-----------------------------------------------------------------------------------
List of settings

That is all it showed

https://iristechnologies-help.zendesk.com/agent/tickets/18211

**Comment by danielng01** [comment]
Can you try to disable Automatic Brightness from your macOS
or disable Night Shift
or delete conflicting programs like f.lux

**Comment by danielng01** [comment]
Update Catalina again

**Comment by danielng01** [comment]
Add this as FAQ to the website

**Comment by valeksa1428** [comment]
https://iristech.co/faq/iris-flashes-on-macos/
