### ISSUE TITLE
flashes

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#110]
Mac OS 10.14.6
 THe app is starting to have intermitant flashes when using it
No other similar apps
Auto brightness is turned off, no other similar apps
https://iristechnologies-help.zendesk.com/agent/tickets/18600

**Comment by danielng01** [comment]
Update the macOS Catalina again

**Comment by danielng01** [comment]
TODO add FAQ for this

**Comment by valeksa1428** [comment]
https://iristech.co/faq/iris-flashes-on-macos/
