### ISSUE TITLE
possible malware issue?

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#115]
I found that Iris tries to access this registry key:

\Registry\Machine\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\996E.exe
see here

What exactly is going on here? This 996E is known malware.

https://iristechnologies-help.zendesk.com/agent/tickets/19017

**Comment by danielng01** [comment]
No, we don't 

More info how

Maybe he is using cracked version of Iris and not from the official website

**Comment by danielng01** [comment]
Add FAQ to only download Iris from the official website to avoid this

**Comment by valeksa1428** [comment]
https://iristech.co/faq/where-to-download-iris-from/
