### ISSUE TITLE
app constantly asks for entering of activation code

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#2]
Macbook air Mojave 10.14.5
Iris Pro
I am continually being asked to resubmit the code below. It does not save - it reverts back to the free trial continually and I get continual messages that the free trial will expire
have reinstalled a few times and restarted.
When I enter the code it always says thank you for your purchase and all seems well (I can access the Pro features) but eventually, it starts counting down as per the free trial again.  When I restart it is fine

**Comment by danielng01** [comment]
Fixed
