### ISSUE TITLE
app keeps asking for activation, shows error operation canceled, maybe you are not connected to the internet? when its connected

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#3]
Windows 10
Iris Pro
I’ve activated Iris on my work laptop several times, and every few days, I get a message that my trial has expired and asking me to buy Iris. I already purchased Iris Pro. This time, nothing happens when I put in my activation code
 it says “operation canceled, maybe you are not connected to the internet?”. I am connected
The administrator has had to set up Iris using the activation code twice already. This will be the third time. I need it to continue working without this extra step. I’m using a PC with Windows 10 Enterprise

**Comment by danielng01** [comment]
fixed maybe
