### ISSUE TITLE
susbcription problem

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#35]
can't activate subscription, shows expired
in system code says unused
codes: s-Tteg and s-dYNc

**Comment by valeksa1428** [comment]
same problem: s-Fiim

**Comment by danielng01** [comment]
Пробвах под Windows 
И в момента работи
s-Tteg

**Comment by danielng01** [comment]
могат ли да пробват пак
На какъв OS са и коя версия на Iris
