### ISSUE TITLE
friend invite doesn't work + trial panel error

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#44]
https://iristech.co/i/rYF8U
neither person gets 1 month free even after syncing

when trying to add time to the trial in the support panel get this error message
![update trial](https://user-images.githubusercontent.com/51370339/62887459-f1e1a200-bd45-11e9-9c7a-82e44521cc5a.jpg)

**Comment by danielng01** [comment]
това трябва да е оправено
