### ISSUE TITLE
external monitors problem

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#45]
wondering if it is possible to run Iris (or any other Night/blue light filter) on multiple external monitors via Docking station (Displaylink) on Ubuntu. I have tried flux, Iris, and redshift to no avail. It only works on the primary display (laptop screen) but the multiple external displays remain unchanged.
Note: I am currently using Dell XPS 13 9360 laptop connected to Dell D3100 docking station with two external AOC monitors.

high level api doesn't work

**Comment by danielng01** [comment]
High-level API works only on Windows

We don't have a solution for Linux

What you can try is to use the Overlay mode

**Comment by danielng01** [comment]
or use some other cable like VGA or HDMI
