### ISSUE TITLE
Iris makes cursor invisible and laggy

### ISSUE THREAD

**Issue by valeksa1428** [iris-technologies/iris-user-issues#99]
Windows 7 Enterprise – Service pack 1 64 bit
Iris 1.1.9

First Pic is showing with IRIS on.  I placed the cursor over a coloured cell, as you can see there is no outline, and it would be invisible had it been over a white cell.
![image001](https://user-images.githubusercontent.com/51370339/66429785-7177ae80-ea21-11e9-9264-94052b561e8c.png)
This screenshot is with IRIS paused, you can see there is a very clear and visible outline on the cross-shaped cursor
![image002](https://user-images.githubusercontent.com/51370339/66429798-776d8f80-ea21-11e9-82b9-608d8e1b177c.png)
This screenshot is with an overlay.  It makes the cursor visible, but this picture captures exactly what I am meaning by “laggy” and “slow” you can see the cursor has a shadow, or tail as it does not move smoothly…
![image003](https://user-images.githubusercontent.com/51370339/66429813-7e949d80-ea21-11e9-9756-17528ad9caf0.png)
Here is an example in outlook, where you can see where my cursor is placed and the cursor when trying to reposition it.  I underlined where my cursor was and what it looks like when I try to reposition it.
![image004](https://user-images.githubusercontent.com/51370339/66429828-86ecd880-ea21-11e9-929e-58658cd281db.png)
This is a similar picture when IRIS is paused
![image005](https://user-images.githubusercontent.com/51370339/66429838-8f451380-ea21-11e9-8c33-8c4cdcaccde9.png)

https://iristechnologies-help.zendesk.com/agent/tickets/18062

**Comment by valeksa1428** [comment]
version 1.2.0 fixes the issue

**Comment by danielng01** [comment]
I don't think so

This is caused by High-level API and the user needs to switch to low-level api

**Comment by danielng01** [comment]
switch to low-level api

add this as FAQ

**Comment by valeksa1428** [comment]
https://iristech.co/faq/iris-cursor-issue-fix/
